### ISSUE TITLE
Failed generate-genesis 

### ISSUE THREAD

**Issue by artjoma** [rzmahmood/ethereum-pos-testnet#5]
`./prysmctl testnet generate-genesis --fork=capella --num-validators=2 --chain-config-file=./config.yml --geth-genesis-json-in=./genesis.json --output-ssz=./genesis.ssz --geth-genesis-json-out=./genesiss.json`

```
INFO[0000] Specified a chain config file: ./config.yml   prefix=genesis
INFO[0000] No genesis time specified, defaulting to now()  prefix=genesis
INFO[0000] Delaying genesis 1696420459 by 0 seconds      prefix=genesis
INFO[0000] Genesis is now 1696420459                     prefix=genesis
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1702abf]

goroutine 1 [running]:
github.com/prysmaticlabs/prysm/v4/cmd/prysmctl/testnet.generateGenesis({0x242da70, 0xc000056120})
        /home/art/dev/eth-custom/devnet/prysm/cmd/prysmctl/testnet/generate_genesis.go:279 +0x6ff
github.com/prysmaticlabs/prysm/v4/cmd/prysmctl/testnet.cliActionGenerateGenesisState(0xc00031fd40)
        /home/art/dev/eth-custom/devnet/prysm/cmd/prysmctl/testnet/generate_genesis.go:179 +0x1c9
github.com/prysmaticlabs/prysm/v4/cmd/prysmctl/testnet.glob..func1(0x32161a0?)
        /home/art/dev/eth-custom/devnet/prysm/cmd/prysmctl/testnet/generate_genesis.go:70 +0x2e
github.com/urfave/cli/v2.(*Command).Run(0x32161a0, 0xc00031fd40, {0xc000b00850, 0x7, 0x7})
        /home/art/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:274 +0x9eb
github.com/urfave/cli/v2.(*Command).Run(0x3216040, 0xc00031fc40, {0xc000572380, 0x8, 0x8})
        /home/art/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:267 +0xc4d
github.com/urfave/cli/v2.(*Command).Run(0xc000b0e000, 0xc00031fb00, {0xc000052090, 0x9, 0x9})
        /home/art/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:267 +0xc4d
github.com/urfave/cli/v2.(*App).RunContext(0xc0002665a0, {0x242da70?, 0xc000056120}, {0xc000052090, 0x9, 0x9})
        /home/art/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
        /home/art/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:309
main.main()
        /home/art/dev/eth-custom/devnet/prysm/cmd/prysmctl/main.go:23 +0x8e
```

**Comment by rzmahmood** [comment]
Interesting, I thought this issue was resolved on the prysm side. I'll investigate.

**Comment by rzmahmood** [comment]
Tried this repo on a fresh laptop and no issues with the submoduled versions. Some versions of prysm have that bug.

**Comment by CoNETProject** [comment]
My case is GETH side has:
```
Post-merge network, but no beacon client seen. Please launch one to follow the chain! 
Post-merge network, but no beacon client seen. Please launch one to follow the chain! 
Post-merge network, but no beacon client seen. Please launch one to follow the chain! 
```
Same as OffchainLabs [eth-pos-devnet](https://github.com/OffchainLabs/eth-pos-devnet)

**Comment by rzmahmood** [comment]
@CoNETProject 
What were the steps to replicate the issue and what machine/operating system are you running it on?

**Comment by artjoma** [comment]
> Interesting, I thought this issue was resolved on the prysm side, I'll investigate. Particular versions of prysm will cause this issue.
> 
> Are you using the version submoduled in this repo? @artjoma

I solved this issue using Prysm 4.0.8.

**Comment by artjoma** [comment]
> My case is GETH side has:
> 
> ```
> Beacon client online, but never received consensus updates. Please ensure your beacon client is operational to follow the chain!
> Beacon client online, but never received consensus updates. Please ensure your beacon client is operational to follow the chain!
> Beacon client online, but never received consensus updates. Please ensure your beacon client is operational to follow the chain!
> ```
> 
> Same as OffchainLabs [eth-pos-devnet](https://github.com/OffchainLabs/eth-pos-devnet)

I had same issue with OffchainLabs. Look carefully at : https://github.com/rzmahmood/ethereum-pos-testnet/blob/main/testnet.sh

**Comment by rzmahmood** [comment]
@CoNETProject yep, I've added [CI](https://github.com/rzmahmood/ethereum-pos-testnet/actions/runs/6417549448/job/17423540159) which is passing on ephemeral environments. If you follow the steps in the guide or use appropriate GETH/PRYSM versions you should have no issues.

Feel free to reopen if your issues aren't resolved
